variables:
  DISTRIBUTION_VER: "buster"
  CI_APT_PREFIX: "k8s-1.15"

image: docker.git.sos.ethz.ch/isg/debian-ci-base-int:$DISTRIBUTION_VER

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - rm -Rf obj-x86_64-linux-gnu || /bin/true
    - dpkg-buildpackage -b -us -uc
    - mv ../*.deb . # GitLab can't copy from the parent directory...
  artifacts:
    name: packets
    expire_in: 3 months
    paths:
      - '*.deb'

deploy_to_apt:
  stage: deploy
  script:
    - echo "Deploying package to $CI_APT_PREFIX prefix and $DISTRIBUTION_VER version"
    - sudo -u repo aptly repo add $CI_APT_PREFIX *.deb
    - sudo -u repo aptly publish update $DISTRIBUTION_VER $CI_APT_PREFIX
  only:
    - tags
  tags:
    - apt
